### ISSUE TITLE
PowerShell is there but not there?

### ISSUE THREAD

**Issue by goigle** [ms-iot/content#1014]
This sounds stupid, I know.
The page is not in the GitHub repo and the website redirects you to a page not found.
https://ms-iot.github.io/content/en-US/win10/samples/PowerShell.htm
However, while loading, you can see the page is in fact there.
I hit the stop button while it was loading and got the above link.

**Comment by IoTGirl** [comment]
Hi Goigle,
That link loads for me. Are you sure you are not having connection problems?
Sincerely, IoTGirl

**Comment by goigle** [comment]
Sorry, I should have been more clear. That link loads for me, the page it is hosted on says "Page not found."
https://developer.microsoft.com/en-us/windows/iot/samples/PowerShell.htm#pagenotfound
Which I get to by following this link: https://ms-iot.github.io/content/en-US/win10/samples/PowerShell.htm

On what actually happens to be your answer here:
https://social.msdn.microsoft.com/Forums/en-US/f8ea9432-ac37-45fd-97a2-63e6ebc56997/how-to-connect-to-university-wifi-requires-username-and-password?forum=WindowsIoT

It is almost definitely not a connection issue as I can see the content load on the page, but while it's loading it then redirects to a page not found so if that is a connection issue then removing all the loaded content on the page is not good.

**Comment by goigle** [comment]
OK, so it looks like the page redirects to "page not found" after getting a moved permanently header
![screenshot](http://i.imgur.com/beRwsN8.jpg)

**Comment by IoTGirl** [comment]
I am not sure where you are getting that link. It does not go to page not found for me. Have you refreshed your browser cache?

**Comment by goigle** [comment]
I got the link from one of your answers on the MSDN forums.
I have checked on 2 different computers using Edge, Chrome, and Pale Moon (Firefox variant) and cleared the caches just to be sure.

Is it possible that your cache is the reason you are not experiencing the problem? What browser are you using?

**Comment by IoTGirl** [comment]
I actually use three browsers in my checking - IE Edge & Chrome.  I have gone back to the link and changed the HTTPS to HTTP and I suspect it will reroute correctly for you now and avoid the issue you were hitting.

**Comment by goigle** [comment]
Ah OK, I see what it is. The link is now a direct one:  
Old: https://ms-iot.github.io/content/en-US/win10/samples/PowerShell.htm  
New: http://developer.microsoft.com/en-us/windows/iot/docs/powershell

The new one does work, thanks!

**Comment by IoTGirl** [comment]
Excellent! Thank you for your confirmation.
