### ISSUE TITLE
404 link in documentation

### ISSUE THREAD

**Issue by OutsourcedGuru** [ms-iot/content#1018]
In the page [Developing Background Applications](https://developer.microsoft.com/en-us/windows/iot/docs/backgroundapplications) is a reference to a dead link.  It's the one which should point to the documentation of the template itself:

http://go.microsoft.com/fwlink/?LinkID=533884&clcid=0x409

It doesn't work however.  I've searched for the actual page but I don't think it was ever documented, tbh.

This link appears again in the page [Writing Apps](https://developer.microsoft.com/en-us/windows/iot/docs/buildingappsforiotcore) and results in the same Page Not Found error.

**Comment by rachitb777** [comment]
Thanks for reporting the issue. The link has been fixed.
