### ISSUE TITLE
Any chance of getting the OpenCV sample for C#?

### ISSUE THREAD

**Issue by enghch** [ms-iot/content#1034]
Are there are any plans to port the OpenCV sample to C#? That would make my life so much easier.

**Comment by IoTGirl** [comment]
Hi enghch,

I know of no current plans to convert this sample but I have let the IoT Team know of your request.

Sincerely,
IoTGirl

**Comment by djaus2** [comment]
Wrt getting it working in C# possibly some interop might work but then you would lose performance.
Without a native C# version of the code you are stuck with interop.
A native C# version is beyond the cope of things here.
You might be best to push this issue at http://opencv.org/

**Comment by enghch** [comment]
Thanks @IoTGirl and @djaus2. I've been working on piecing together an OpenCV-based UWP app (for IoT and non-IoT devices) with a C#/XAML front end. It hasn't been easy to find all the missing pieces but I think I've almost got it all working. As you mentioned, for performance reasons, I've written all the low-level image manipulation in a C++ Windows Runtime Component. All the UI and higher-level functionality is in a C# app that depends on the C++ WRC. I should probably write a blog post on all the steps required to make it work.

**Comment by djaus2** [comment]
Yes I agree that is the way to go. UI in C# interoping with the CV code. I would be interested in seeing the code when done and your blog.
