### ISSUE TITLE
Docpage of Wifi Dongles breaks itself by forwarding to a 404

### ISSUE THREAD

**Issue by michaelosthege** [ms-iot/content#1036]
The "See list of supported WiFi Dongles" link on the "Your SD card is ready" page of the IoT Core Dashboard points to:
[http://ms-iot.github.io/content/en-US/win10/SupportedInterfaces.htm#WiFi-Dongles](http://ms-iot.github.io/content/en-US/win10/SupportedInterfaces.htm#WiFi-Dongles)
When I browse to that page, the correct content is visible for about half a second. Then the page forwards to:
[https://developer.microsoft.com/de-de/windows/iot/docs/SupportedInterfaces.htm#pagenotfound](https://developer.microsoft.com/de-de/windows/iot/docs/SupportedInterfaces.htm#pagenotfound)

This is very annoying..

**Comment by rachitb777** [comment]
Thanks for repoting the issue. We will fix iot dashboard to points to correct link which is https://developer.microsoft.com/en-us/windows/iot/docs/hardwarecompatlist#WiFi-Dongles

**Comment by michaelosthege** [comment]
I hope that you are aware that the real issue is NOT with the IoT Dashboard, but the way how the docs were restructured. As far as I know, **the forwarding is broken for many other links** pointing towards http://ms-iot.github.io

Another example of a broken link is [http://ms-iot.github.io/content/en-US/win10/samples/PowerShell.htm](http://ms-iot.github.io/content/en-US/win10/samples/PowerShell.htm)

And I'm sure that there are many more on stackverflow and elsewhere...
