### ISSUE TITLE
LightningPerformance.md Page outdated

### ISSUE THREAD

**Issue by ghost** [ms-iot/content#1042]
Is there any update on performance with RS1/RS2/RS3? The page https://github.com/ms-iot/content/blob/develop/en-US/Docs/LightningPerformance.md has not been updated since TH2!

**Comment by MahmoudGSaleh** [comment]
Agreed, it's taken a long time.
At this point, we don't have new numbers to post, But, I have added it to the team's backlog, so they can be updated, and hopefully released with next round of doc updates for the next release of IOTCore .
