### ISSUE TITLE
Arduino Wiring Libraries Documentation

### ISSUE THREAD

**Issue by ghost** [ms-iot/content#1059]
[https://github.com/ms-iot/content/blob/develop/en-US/Samples/arduino-wiring/ArduinoWiringComponents.md](url)

**o)** Step 2 should include a step to build the project as this is required before Step 3

**o)** "Step 3: Using the Class from C" should be "Step 3: Using the Class from C#"

**o)** to avoid
_1>Error: Microsoft Visual Studio Remote Debugging Monitor cannot start without a Machine Name. Open project properties and specify a Machine Name under 'Configuration Properties -> Debugging'_
either Step 1 or 2 should include this required step

**o)** as the changes in Package.appxmanifest produce 2 warnings
_Warning		The element 'Capabilities' in namespace 'http://schemas.microsoft.com/appx/manifest/foundation/windows10' has invalid child element 'Capability' in namespace 'http://schemas.microsoft.com/appx/manifest/iot/windows10'. List of possible elements expected: 'CapabilityChoice' in namespace 'http://schemas.microsoft.com/appx/manifest/foundation/windows10' as well as 'Capability' in namespace 'http://schemas.microsoft.com/appx/manifest/uap/windows10' as well as 'Capability, DeviceCapability' in namespace 'http://schemas.microsoft.com/appx/manifest/foundation/windows10'.	BackgroundApplication1	D:\VS 2017\Universal Windows Apps\ArduinoWiringApplication1\BackgroundApplication1\Package.appxmanifest	55_	

_Warning		The element 'BackgroundTasks' in namespace 'http://schemas.microsoft.com/appx/manifest/foundation/windows10' has invalid child element 'Task' in namespace 'http://schemas.microsoft.com/appx/manifest/iot/windows10'. List of possible elements expected: 'BackgroundTaskChoice' in namespace 'http://schemas.microsoft.com/appx/manifest/foundation/windows10' as well as 'Task' in namespace 'http://schemas.microsoft.com/appx/manifest/uap/windows10' as well as 'Task' in namespace 'http://schemas.microsoft.com/appx/manifest/foundation/windows10'.	BackgroundApplication1	D:\VS 2017\Universal Windows Apps\ArduinoWiringApplication1\BackgroundApplication1\Package.appxmanifest	46_

may be its a good idea to add something like "the warnings are ok you can proceed.."

**o)** var lib = new ArduinoWiringApplication1.MyArduinoComponent(); raise exception
_System.Runtime.InteropServices.COMException: 'The text associated with this error code could not be found.
Error occurred verifying pin: 29 function: DIGITAL_IO, Error: 80049212: The specified device could not be found on the system. Please Make sure the Lightning driver is enabled. For more information refer to the Lightning Setup Guide: http://ms-iot.github.io/content/en-US/win10/LightningSetup.htm'_

should the beginning of "Building Arduino Wiring Libraries in 4 Easy Steps" list enabled Lightning drivers with a link to Lightning Setup Guide ?

**Comment by IoTGirl** [comment]
Hi Andre,
Again, if you make a pull request I can get it reviewed. Note: I believe the file you mention above is in content/en-US/Samples/arduino-wiring/.
Sincere thanks,
IoTGirl
