### ISSUE TITLE
'ApplicationInsights' does not exist in the namespace 'Microsoft'

### ISSUE THREAD

**Issue by GouthamiJJ** [ms-iot/content#1111]

**Comment by baotrung1309** [comment]
I'm trying to run the sample "ZigbeeAdapter" and I also had the same problem.

public App()
        {
            Microsoft.ApplicationInsights.WindowsAppInitializer.InitializeAsync(
                Microsoft.ApplicationInsights.WindowsCollectors.Metadata |
                Microsoft.ApplicationInsights.WindowsCollectors.Session);
            this.InitializeComponent();
            this.Suspending += OnSuspending;
        }
The error log: The type or namespace name 'ApplicationInsights' does not exist in the namespace 'Microsoft' (are you missing an assembly reference?)

Did anyone solve this problem?? Thanks in advanced!

best Regards,
Trung.
