### ISSUE TITLE
EULA Missing?

### ISSUE THREAD

**Issue by ianlee74** [ms-iot/content#1157]
The IoT Core Dashboard has a link ("View software license terms") in the footer that points to:
https://ms-iot.github.io/content/en-US/iotcoreeula.pdf

This file doesn't appear to exist. Does this file need to be restored to this repo or does the IoT Core Dashboard app need to be updated?

**Comment by IoTGirl** [comment]
To repro:
1. Open dashboard
2. Go to "Set Up New Device" page
3. At the bottom of the page select "View software license terms"
RESULTS:
Expected: Eula to be displayed
Actual: 404 as file seems to be missing from ms-IoT GITHUB

NOTE: I have found some history here https://github.com/ms-iot/content/commit/a20514c50d9bf9e1d19692cee8cc4e1cd36c6e75  and https://github.com/ms-iot/content/blob/67bbe9dbec0dc3018639860978c352b1a62c4992/en-US/iotcoreeula.pdf

**Comment by rachitb777** [comment]
The link is now fixed.

**Comment by ianlee74** [comment]
Confirmed. Thanks!
