### ISSUE TITLE
Content issue - Where do you buy an "Askey Turbomate E1" - its not available anywhere

### ISSUE THREAD

**Issue by brianro** [ms-iot/content#1166]
On the page iot.htm you reference this product "Askey Turbomate E1" but there is no reasonable way to acquire it in the US. Could you please help us get it or remove it as an example of tech please?

**Comment by IoTGirl** [comment]
Hi @brianro,
Following the link gets you to the company website.  I recommend following up with the contact closest to you.  http://www.askey.com.tw/contact.html or emailing sales@askey.com.tw and asking about availability.
Sincerely,
IoTGirl

**Comment by brianro** [comment]
You are trying to create a following. Is linking in a product that is not available from the website or any of the vendors a good idea? Have you tried to buy one?
