### ISSUE TITLE
Cortana not enabled on Windows 10 IOT (OS Version: 10.0.15063.251), Raspberry PI 3 Model B

### ISSUE THREAD

**Issue by brvinodh** [ms-iot/content#1175]
Hi, 

I have updated to the latest build of Windows IOT and have done the following as per the documentation. 

1. Plugged in a Microphone with Speaker, this is recognized on the Device Portal Page as well, i have attached the screenshot. 
![image](https://user-images.githubusercontent.com/29249012/27839167-d159c766-610c-11e7-86b3-87db53aadf69.png)

2. Raspberry Pi 3 is connected to Monitor via HDMI cable

3. Im not able to turn on Cortana; the radio button is disabled, The screenshot is attached below. 

![image](https://user-images.githubusercontent.com/29249012/27839214-440f2d5a-610d-11e7-80ee-1286575f47a1.png)

4. Option "Start Cortana on Boot" is also not available in the Device portal home Page. 

Can you please help.

Thanks
Vinodh

**Comment by rachitb777** [comment]
@brvinodh Can you check if Cortana app is installed on the image. You can do this by running 
`iotstartup list` using PowerShell or SSH.

**Comment by zhuridartem** [comment]
Hi brvinodh.
This is a symptom of Cortana App not present in the image. 
An update does not add new optional feature packages, and Cortana App is included in such package. 
Easiest way to pick it up is to clean install latest image.

**Comment by brvinodh** [comment]
Hi zhuridartem, 

Thank Let me perform a fresh install and check back.
