### ISSUE TITLE
support for the pi camera

### ISSUE THREAD

**Issue by karann-msft** [ms-iot/content#1188]
I was speaking to a customer who is doing something very interesting with Win10 IOT and electric cars. He wants to be able to control the pi camera that connect to the board using the CSI camera port.
Is this supported? Either yes or no, is this documented?

**Comment by ghost** [comment]
for future questions not related to hosted github projects please use https://developer.microsoft.com/en-us/windows/iot/Community
the release notes you will find on the download page https://developer.microsoft.com/en-us/windows/iot/Downloads contain information about Raspberry Pi Camera Support

**Comment by saraclay** [comment]
@karann-msft Hi Karan, it would be in your customer's best interest to reach out to Raspberry Pi to express the desire to use the Pi Camera using the CSI camera port.
