### ISSUE TITLE
Windows 10 IoT Preview Build 16241 - IoT Remote Client Shows Blank Screen

### ISSUE THREAD

**Issue by Tornadocraver** [ms-iot/content#1191]
Apart from my other issue on the other thread, it seems like Preview Build 16241 has an issue with the IoT Remote Client app. The Raspberry Pi 3 B is running Windows 10 IoT Insider Preview Build 16241. I did check (multiple times) that the remote server is enabled in the Device Portal. When I first try to connect, the little loading circle spins for a few seconds and then disappears (I assume that means that it's connected).

![image](https://user-images.githubusercontent.com/20540006/28503972-6558814e-6fdd-11e7-9337-8ec8494ac2fa.png)

However, after the loading circle disappears, all I get is a white screen.

![image](https://user-images.githubusercontent.com/20540006/28503923-b71c0a9c-6fdc-11e7-9406-45a700f0a2d5.png)

I went to the Device Portal and took a few screenshots which appear normal. I also plugged the Pi into my TV via an HDMI cable, and that works fine as well. Any ideas on what is going on here? This project is on hold for me (in addition to the other one) until it gets resolved. Thanks for your time and work!

**Comment by ghost** [comment]
for questions not related to hosted github projects or developer questions please use https://developer.microsoft.com/en-us/windows/iot/Community or the feedback hub if you discover any issue

**Comment by saraclay** [comment]
@Tornadocraver Hi Micah - Is this issue still persisting for you?

**Comment by Tornadocraver** [comment]
@saraclay Hi Sara,

I am sorry I didn't post that I resolved this issue a while back (as I procured the solution on another forum). I ended up flashing the latest stable build on the Pi that was giving me the issue. By the time I wanted to try the preview build again, a new version had been released and it no longer gave me the issue.

Thanks for reminding me about this, and I'll close it now.

**Comment by ErikParso** [comment]
> @saraclay Hi Sara,
> 
> I am sorry I didn't post that I resolved this issue a while back (as I procured the solution on another forum). I ended up flashing the latest stable build on the Pi that was giving me the issue. By the time I wanted to try the preview build again, a new version had been released and it no longer gave me the issue.
> 
> Thanks for reminding me about this, and I'll close it now.

Hello, in what version is this fixed ?
