### ISSUE TITLE
HID Injector Sample deployment docs feedback

### ISSUE THREAD

**Issue by hansmbakker** [ms-iot/content#1214]
On https://github.com/ms-iot/content/blob/develop/en-US/Samples/HidInjector.md it is stated that you need to copy the cab file and need to run `ApplyUpdate -stage Microsoft.HidInjectionSample.HidInjectionSample.cab`.

However I think that on current Insider Preview builds you can just upload cab updates through the web interface.

![image](https://user-images.githubusercontent.com/3463496/29249379-9765affc-802e-11e7-9d92-3b00881b67ee.png)

**Comment by saraclay** [comment]
Hi @wind-rider it looks like this issue has been resolved.
