### ISSUE TITLE
Document containers

### ISSUE THREAD

**Issue by sixcorners** [ms-iot/content#1271]
Pull request #1252 added something about container hosting on "64-bit editions of Windows 10 IoT Core". Where would I go to find out more about this? Could some documentation be added or could I be given a link to some?

**Comment by saraclay** [comment]
Hi @sixcorners, while we're working to get more container-related documentation out there, we have a few things to get you started:

- This sample is designed to work with Windows containers on Windows 10 IoT Core and Windows IoT Enterprise: [https://github.com/Microsoft/Windows-iotcore-samples/tree/master/Samples/ContainerWebSocket ](https://github.com/Microsoft/Windows-iotcore-samples/tree/master/Samples/ContainerWebSocket )

-And here are some other links that, while they talk a bit more about IoT Edge, do also talk about containers: [https://docs.microsoft.com/en-us/azure/iot-edge/how-to-install-iot-core](https://docs.microsoft.com/en-us/azure/iot-edge/how-to-install-iot-core), [https://docs.microsoft.com/en-us/azure/iot-edge/tutorial-simulate-device-windows#prerequisites](https://docs.microsoft.com/en-us/azure/iot-edge/tutorial-simulate-device-windows#prerequisites)
