### ISSUE TITLE
Samples page all / none filter style not changed on clicking

### ISSUE THREAD

**Issue by rachitb777** [ms-iot/content#1294]
https://developer.microsoft.com/en-us/windows/iot/samples

When page loads, all should be selected (black background). On changing to none, none should have back background.

**Comment by saraclay** [comment]
Related to this current TFS bug: https://microsoft.visualstudio.com/OS/_workitems?id=14967667&_a=edit

**Comment by saraclay** [comment]
Bug has been resolved by Namrata - just need to push to PROD.
