### ISSUE TITLE
Coordinator Enabled

### ISSUE THREAD

**Issue by kburgoyne** [ms-iot/content#1309]
As per some Digi forum responses: New XBee devices have larger processors which already contain both Router and Coordinator firmware.  Older XBee's required a different firmware load between the two as implied in this document.  There is no longer different firmware loads for Router versus Coordinator.  Instead there is a "CE Coordinator Enable" setting under "Networking".  Set to 0 (zero) for Router, and 1 (one) for Coordinator.

**Comment by saraclay** [comment]
Thank you for the insight.
