### ISSUE TITLE
Need clarification for no display connection instructions

### ISSUE THREAD

**Issue by BarsikTheCaT** [ms-iot/content#1369]
The third paragraph "Click on Configure Device and enter your network credentials. This will connect your board to the network." does not make any sense. What are the network credentials authors are referring to? Nothing like that was mentioned until that point and it has nothing to do with router or network credentials.

**Comment by saraclay** [comment]
Hello - can you please send me the link to what you're referring to?

**Comment by BarsikTheCaT** [comment]
I am referring to this page: https://developer.microsoft.com/en-us/windows/iot/getstarted/prototype/setupdevice

**Comment by saraclay** [comment]
Thank you, @BarsikTheCaT. We're investigating this.

**Comment by saraclay** [comment]
We've clarified the instructions.
