### ISSUE TITLE
Official name of Windows flavor as supplied with Galileo IoT kit? 

### ISSUE THREAD

**Issue by pfalcon** [ms-iot/content#138]
I'd like to know which name I should use to refer to Windows version as supplied on an SD card in Galileo IoT - in such a way that both MicroSoft people (including those who don't deal with IoT program) and rest of the world understand me.

So far, it's rather confusing - is it "Windows On Devices", "Windows For Devices", "Windows IoT", "Windows Headless", or something completely different?

P.S. I'm not sure this is the right github project to report this to, so feel free to refer me to the better project to submit such issues against, but please kindly accept such issue reports via github - you created account here to improve outreach to community, right?

**Comment by Shak7** [comment]
Hi pfalcon,
Me too I find this a bit confusing. Nothing official here but, to add to the list of names... The download link on developers site for the files says "Microsoft Windows For Intel Galileo". I used that in my GitHub descriptions. To me, this sounds clear. Again, nothing official.

**Comment by ooeygui** [comment]
Hello All,
I'm terribly sorry for the confusion. Officially the version of windows supplied through this program is "Windows through the Windows Developer Program for IoT". 

We have not been consistent in the docs; this only adds to the confusion. I'm going to take an action to fix this so it is at least consistent (if wordy).

We are on GitHub with active projects; this is the primary place to discuss and fix bugs and add features, add project links, and update or clarify docs. We are actively engaged and love interacting with Makers.

**Comment by pfalcon** [comment]
@Shak7: Thanks for feedback. I however would prefer not to cal it "For Intel Galileo", because it sends a message that this is an adhoc, once-off version, to be gone soon (as any hardware is obsoleted/displaced very soon), and thus not interesting to wide audience. I really hope that Galileo board is just an example of deployment of this new version of Windows, and it will be supported and available for many customer solutions.

**Comment by pfalcon** [comment]
@ooeygui: Thanks for reply and reassuring that the issue reports are welcome!

> "Windows through the Windows Developer Program for IoT"

Thanks for confirming the official name. But it's indeed quite wordy. I then hope that "Windows for IoT" is good enough informal abbreviation (my main concern is that any blog/forum posts I (others too surely) do were/could be understood by other people, and be well discoverable via search engines).

**Comment by Shak7** [comment]
Yes, I did changed the name for the official one in my description. Thanks for everything.
