### ISSUE TITLE
Dragonboard 410c analog audio output

### ISSUE THREAD

**Issue by endyb66** [ms-iot/content#1390]
On the Dragonboard 410c, there is a analog audio header (J7). When connecting small speakers to the direct output SPKR_L and SPKR_R, everything works. But i need to attach a 3.5mm jack, sadly on These pins is no Audio Signal and there is no audio device listed to Change to.

**Comment by saraclay** [comment]
Hi @endyb66 - what exactly is your question here? What information are you looking for?

**Comment by endyb66** [comment]
Hi @saraclay I need to know on how to use the analog audio output on Windows Iot Core with the Dragonboard 410c, because it seems that this is not possible due to a missing driver or something.

**Comment by saraclay** [comment]
Hi @endyb66, have you looked into the hardware modifications recommended here? https://developer.qualcomm.com/qfile/29468/lm80-p0436-43_c_stereo_connector_and_audio_routing_on_dragonboard_410c_application_note.pdf

**Comment by endyb66** [comment]
@saraclay, yes i have, but it simply does not work. I read in the document there, that for e.g. on linux based systems it has to be modified something,

**Comment by saraclay** [comment]
Have you tried to configure the audio output via the [Windows Device Portal](https://docs.microsoft.com/en-us/windows/iot-core/manage-your-device/deviceportal)?

**Comment by endyb66** [comment]
@saraclay, i have only one output device listed there.

**Comment by saraclay** [comment]
Could you file a bug on our forum? Apologies - https://social.msdn.microsoft.com/Forums/en-US/fad1c6a0-e578-44a7-8e8d-95cc28c06ccd/need-logs-if-your-device-hasnt-updated-to-the-latest-iotcore-version?forum=WindowsIoT

**Comment by endyb66** [comment]
@saraclay, couldn't you reproduce the issue?
