### ISSUE TITLE
node.js

### ISSUE THREAD

**Issue by nishanthkarthik** [ms-iot/content#160]
node.js 0.12.0 doesnt work on Galileo Gen 1, whereas, 0.11.9 version works fine. I think this should be included specifically on the webpage. This is my first time opening an issue and wasnt sure where to. Thanks.

**Comment by ooeygui** [comment]
Thanks for the report. This is a good place to report a problem. If you want to take a crack at getting 0.12.0 working, here's the docs for figuring out what doesn't work: http://ms-iot.github.io/content/Forwarders.htm.

**Comment by nishanthkarthik** [comment]
Also, v 0.11.9 doesn't load <i>./ms-iot-wiring.node</i>. I tried 0.10.0.0 and it works with  <i>./ms-iot-wiring.node</i>. Hence, it would be better if it is clearly stated on <i>node.js tutorial</i> page to use v 0.10.0 for using <i>./ms-iot-wiring.node</i>. Thanks.

**Comment by ooeygui** [comment]
Thank you for the report. I'll look into this.

**Comment by ooeygui** [comment]
Node.js is supported on Windows 10. We won't be doing new feature work on Galileo. See our FAQ on this - http://ms-iot.github.io/content/Faqs.htm#galileo
