### ISSUE TITLE
Tutorial only shows how to open existing projects

### ISSUE THREAD

**Issue by atrauzzi** [ms-iot/content#249]
Would be better if a file-new progression was shown.  Maybe more information about targeting IoT devices.  From existing projects too.

**Comment by ooeygui** [comment]
We have two walk through:
a graphical one:
http://ms-iot.github.io/content/win10/samples/HelloWorld.htm
and Console:
http://ms-iot.github.io/content/win10/samples/ConsoleApp.htm

As far as IoT devices, we will be adding new projects, samples and documentation.

**Comment by atrauzzi** [comment]
Sounds good :)
