### ISSUE TITLE
Need to remind people to add another trusted host after changing machine name:  http://ms-iot.github.io/content/win10/samples/PowerShell.htm

### ISSUE THREAD

**Issue by bobfr** [ms-iot/content#295]
need to do this

Set-Item WSMan:\localhost\Client\TrustedHosts -Value <new machine name> after changing name of rpi,

should add to instructions here:  http://ms-iot.github.io/content/win10/samples/PowerShell.htm

**Comment by AleksandarDev** [comment]
This.

**Comment by IoTGirl** [comment]
Fixed. Statement is in the latest instance of this document.
