### ISSUE TITLE
No ListServices on RPI2?

### ISSUE THREAD

**Issue by mahilleb-msft** [ms-iot/content#297]
http://ms-iot.github.io/content/win10/tools/CommandLineUtils.htm / https://github.com/ms-iot/content/blob/develop/win10/tools/CommandLineUtils.md
refers to a ListServices utility, which does not seem to be present in the RPI2 image (5/12/2015 release). Not sure whether it's supposed to be there and just missing, or the doc is wrong, and it's not expected to have this (on RPI2).

Thanks, Mark

**Comment by bfjelds** [comment]
created pull request to remove references to ListServices.exe:

https://github.com/ms-iot/content/pull/520
