### ISSUE TITLE
Develop vs gh-pages 

### ISSUE THREAD

**Issue by vasujain** [ms-iot/content#311]
I didn't see changes for my PR reflected at http://ms-iot.github.io/content/win10/SetupMBM.htm . PR was merged to Develop. Should i have sent it to gh-pages branch instead of develop branch ?

**Comment by jongio** [comment]
You did it correctly.  We just converted the file to MD and your changes were lost in the process.  Apologies. We are fixing it.

**Comment by vasujain** [comment]
Thanks You ! However it missed some part of the commit @ https://github.com/vasujain/content/commit/d35ed0ebfefdb8675666e6821178e60a08ea6e8c where i have added an example.

**Comment by ooeygui** [comment]
@vasujain this page has diverged significantly. Would you mind resubmitting your original change?
