### ISSUE TITLE
broken link release notes

### ISSUE THREAD

**Issue by wldevries** [ms-iot/content#374]
The link to the release notes from the win10 for raspberry pi download page is broken

**Comment by markrad** [comment]
This should be fixed soon.
Mark Radbourne (MSFT)

**Comment by bfjelds** [comment]
This appears to be fixed.  http://ms-iot.github.io/content/en-US/Downloads.htm contains a link to http://go.microsoft.com/fwlink/?LinkId=534601 (which redirects to http://ms-iot.github.io/content/en-US/win10/ReleaseNotes.htm).
