### ISSUE TITLE
Extend the SSH service

### ISSUE THREAD

**Issue by mstorsjo** [ms-iot/content#514]
The possibility to remotely administrate the IoT devices over SSH is great! There are a few limitations that I've run into so far:
- Would it be possible to extend the SSH service so that SCP commands also succeed? Currently they fail like this:

```
$ scp foo Administrator@192.168.0.220:
Administrator@192.168.0.220's password: 
exec request failed on channel 0
lost connection
```
- Is it possible to execude commands directly via the SSH command, like on normal unix? That is, doing something like this: `ssh Administrator@192.168.0.220 ipconfig` This fails with the same error as executing SCP: `exec request failed on channel 0`.
- When closing the session by calling `exit`, the ssh session just hangs. When connecting with a graphical application like PuTTY, this probably is ok (since the caller can just close the window), but when connecting from a terminal on linux, this is problematic (when one doesn't want to close the whole terminal).
- Is it possible to set up SSH keys, for logging in without manually typing a password?

I understand that this particular git repo possibly isn't the right place to post such feature requests - I also posted the same comments at https://connect.microsoft.com/windowsembeddedIoT/feedback/details/1620770.

**Comment by alecont** [comment]
Hi mstorsjo, this is great feedback! thx super! We do monitor both the git repo (sorry, I was a bit slow in replying) but thx for entering this on connect.microsoft.com (I just read your suggestions a week ago, and this entry here in GitHub sounded eerily familiar :-))

So, as you know, with Windows 10 we introduced SSH. I think it's great, and we definitely want to add some more features in this area. I'll pass all this feedback to the owners of SSH.

Keep this coming!! :-)
