### ISSUE TITLE
Windows 10 IoT Core WIFI Adapters

### ISSUE THREAD

**Issue by Injac** [ms-iot/content#573]
Hi,

this article needs to be updated, with more in depth information, like a video for each adapter showing it working and with the firmware versions (adapter firmware, version) used.

https://github.com/ms-iot/content/blob/develop/en-US/win10/SetupWiFi.md

I bought the TP-LINK TL_WN725N for my MBM and I cannot make it work.

**Comment by cmaloney-msft** [comment]
Hi Injac, can you share what issues you are seeing with the TL_WN725N? Does the UI show as you having a WiFi adapter install?

**Comment by Injac** [comment]
Hi,
Sorry for the late reply. No the UI did not show up. The adapter has been defective. Everything works fine now.

**Comment by ooeygui** [comment]
We now have a hardware compatibility tab on windowsondevices.com - http://ms-iot.github.io/content/en-US/win10/SupportedInterfaces.htm
