### ISSUE TITLE
Failed to commit pending deployment

### ISSUE THREAD

**Issue by ehigh2014** [ms-iot/content#591]
I use Visual Studio 2015 develop an app and debug on the raspberry pi 2 success.
But when I get the package and use the appx manager from the web to commit deployment, I failed.
Error code : 0x80004005, could you help solve this problem?

**Comment by ehigh2014** [comment]
Reference : http://ms-iot.github.io/content/en-US/win10/tools/Webb.htm

**Comment by bfjelds** [comment]
What kind of app are you using (Blank Application, Background Application, etc)?  Language (C++, C#, etc)?  Do you have the same problem using Blinky or HelloWorld from https://github.com/ms-iot/samples?

**Comment by IoTGirl** [comment]
Closing this issue as there has been no response from the original poster and AppX documentation is available at https://developer.microsoft.com/en-us/windows/iot/win10/backgroundapplications
