### ISSUE TITLE
How to install the driver of usb-to-ttl adapter

### ISSUE THREAD

**Issue by ehigh2014** [ms-iot/content#592]
I've get a USB-to-TTL adapter，but i don't know how to install the driver, then when use this app, i can't find the devices.
how to deal with this problem，and if I use the PL2303 USB-to-TTL adapter, how to do ?

**Comment by ooeygui** [comment]
Assigned to @stjong by github triage

**Comment by ehigh2014** [comment]
I've tried the CP2102 USB to Bridge, can work on the Win10 IoT immediately.

**Comment by IoTGirl** [comment]
Based on the last post I am closing this issue
