### ISSUE TITLE
Raw images for RPi2

### ISSUE THREAD

**Issue by lukeadams** [ms-iot/content#606]
Wish list: 
- Writable .img for non-Windows users (Virtualbox has issues with USB mounting, it would be faster if I could just dd it)
- Encapsulate the IoT tools in a ZIP, not an ISO

**Comment by HeisenbergUncertain** [comment]
I too have some good stuff going for us. gonna get all the good acronyms that are the ones with all the bad letters in them - who knows what they could stand for......
well, it's close enough pay for government vork - fork, sorry !!!!!!!!!!

![greefas2](https://cloud.githubusercontent.com/assets/5224841/9763553/0a5485d8-56bf-11e5-8d9f-b090bb2eee90.jpg)

**Comment by lukeadams** [comment]
Ech. Sorry about the wordy post – I was exhausted at the time.
I updated it for clarity (the acronyms aren't meaningless; the people who could resolve this would know them, otherwise you are a quick google search away...)

**Comment by SunboX** [comment]
Jep, a simple *.img file would be a lot easier to install. Would appreciate it.

**Comment by marcusrussell** [comment]
Thanks for this feedback, but at this team we do not plan to package releases as .img, and instead will make releases via .iso packages.
