### ISSUE TITLE
File Sharing IoT device

### ISSUE THREAD

**Issue by ricl** [ms-iot/content#616]
https://ms-iot.github.io/content/en-US/win10/samples/SMB.htm

When entering the Username to obtain access from the desktop it needs to be of the form

Username: 192.168.1.19\Administrator
Password: {your_password}

**Comment by ooeygui** [comment]
We should break out the username. Simple \Administrator works without having to specify ip

**Comment by IoTGirl** [comment]
Suggested page update has been accepted and merged.
