### ISSUE TITLE
Missing RTM Release notes

### ISSUE THREAD

**Issue by Tapanila** [ms-iot/content#632]
Currently link for RTM release notes takes you to same page as Insider Preview Release notes.
1. Go to http://ms-iot.github.io/content/en-US/Downloads.htm
2. Click Release notes on left
3. Leading into http://ms-iot.github.io/content/en-US/win10/ReleaseNotes.htm

**Comment by marcusrussell** [comment]
Hello Tapanila,

Thank you for your feedback! This issue has been resolved.

Download Windows 10: Release Notes --> http://ms-iot.github.io/content/en-US/win10/ReleaseNotesRTM.htm (10240)

Download Windows 10 Insider Preview: Release Notes --> http://ms-iot.github.io/content/en-US/win10/ReleaseNotes.htm (10556)
