### ISSUE TITLE
Release notes incorrectly mentions support for TPLink WiFi dongle on Raspberry Pi2

### ISSUE THREAD

**Issue by ravindrank** [ms-iot/content#676]
Release notes indicates:
Support for the TPLink WiFi dongle on Raspberry Pi2

We are unable to find any driver in C:\Windows\Inf on RPi2 and do not believe that the wifi adapter is supported on RPi2 (only minnowboard)

**Comment by ricl** [comment]
http://www.ebay.co.uk/itm/like/361362425807?adgroupid=13585920426&hlpht=true&hlpv=2&rlsatarget=kwd-75951457866&adtype=pla&ff3=1&lpid=122&poi=1006976&ul_noapp=true&limghlpsr=true&device=c&chn=ps&campaignid=207297426&crdt=0&ff12=67&ff11=ICEP3.0.0-L&ff14=122&viphx=1&ops=true&ff13=80

also works out of the box (same Broadcom chip as the official adapter).

**Comment by ravindrank** [comment]
Thanks ricl. Aware of that.. Most of those ship from UK .. But anyway the concern is different here.

**Comment by cmaloney-msft** [comment]
Thanks for catching this. You are correct this build does not support the TPLink dongle on RPi2 and there was an error in the release notes. We are updating the release notes.

**Comment by AndreaBeggiato** [comment]
Amazon deliver me this dongle today. There are some plans to support this type of dongle?

**Comment by cmaloney-msft** [comment]
Yes, we are working on this for a future release.

**Comment by ravindrank** [comment]
Thanks for your ack :)

**Comment by volkansarioglu** [comment]
Are you kidding me ? 
We are spending money and time for it, how do you make a mistake in supported device list?
Im not use Windows IoT anymore cause; 
 if you make a mistake in supported device list, you can make a mistake in every where.

**Comment by AndreaBeggiato** [comment]
Hi guys,
you have remove the wrong release note from here http://ms-iot.github.io/content/en-US/win10/ReleaseNotes.htm ,but you have add RPI2 compatibility in the hardware section here http://ms-iot.github.io/content/en-US/win10/SupportedInterfaces.htm

**Comment by HerrickSpencer** [comment]
Thanks for the notice, Andrea.
This is currently in [PR to be removed](https://github.com/ms-iot/content/pull/690)

**Comment by ooeygui** [comment]
This has been removed from the hardware guide.

**Comment by byGao** [comment]
hi cmaloney-msft:
the following page still have wrong list..(about wifi dongles tag..with TP-WN725N part)
http://ms-iot.github.io/content/en-US/win10/SupportedInterfaces.htm

and... when will support TP-WN725N?
please give me a page to follow.
thank you

**Comment by judavi** [comment]
Yes, it's still there... 
![image](https://cloud.githubusercontent.com/assets/1766933/11185526/1436601e-8c4b-11e5-9ecb-204ab1ae3d50.png)

**Comment by ricl** [comment]
It has come (and gone) from that page a few times. :-)

Have patience, it is reported that it IS supported in the, yet to be fully
released - only leaked, 10586 IoT release.

**Comment by byGao** [comment]
ok...
Thanks for your reply.

**Comment by maksii** [comment]
Ahh, amz. It's still in list and it's not working. Are you going to fix it?
