### ISSUE TITLE
WebBased Device Management documentation fixes

### ISSUE THREAD

**Issue by eagle00789** [ms-iot/content#688]
See: https://github.com/ms-iot/content/blob/develop/en-US/win10/tools/Webb.md needs few fixes:

Heading: Additional Information
Change HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\Windows\CurrentVersion\IoT\WebB to HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\Windows\CurrentVersion\IoT\WebManagement and has to be changed 3 times...

**Comment by IoTGirl** [comment]
Fixed. New page is https://developer.microsoft.com/en-us/windows/iot/win10/tools/deviceportal
