### ISSUE TITLE
Does Windows 10 IoT support HDMI to VGA converter ?

### ISSUE THREAD

**Issue by archersmind** [ms-iot/content#703]
Dear Team,

I recently installed Windows 10 IoT on my Raspberry Pi2. But when it boot up I see the screen like below:

![435386973](https://cloud.githubusercontent.com/assets/1461331/11030058/7f8c2d5c-8706-11e5-8cb1-02fc57198b24.jpg)

As one can see in the picture, I use a HDMI to VGA converter for my old monitor. So I doubt If the Windows 10 IoT is support HDMI to VGA converter, cause it's fine when I installed any other linux based os for example Noobs.

Thanks

**Comment by marcusrussell** [comment]
Hello Archersmind,

You might try modifying the config.txt file to configure your device to work with the VGA converter and monitor.  Try this example:
[config.txt](https://github.com/ms-iot/content/files/52206/config.txt)
