### ISSUE TITLE
GetStarted.htm has a typo - "....Raspbery Pi 2"

### ISSUE THREAD

**Issue by marcusrussell** [ms-iot/content#743]
"Steps to set up Raspbery Pi 2" includes a typo.  "Raspbery" should be spelled "Raspberry"
http://ms-iot.github.io/content/en-US/GetStarted.htm

**Comment by ghost** [comment]
Fixed in pull request https://github.com/jasgroce/content/commit/3042e0cdb6a6042ff3e5c7d1f789ee4334fd23c5
