### ISSUE TITLE
Invalid URL to T&C from new device setup scren in IoT Dashboard app

### ISSUE THREAD

**Issue by peterblazejewicz** [ms-iot/content#792]
Hi,
I've a problem of finding correct way to report this. I've just install IoT Dashboard and successfully configured SD Card for Raspberry PI device. During card setup I had to accept T&C terms. Default auction of this leads to some page on MS documentation page, but the link is broken. The link is a typical MS shortened url:
http://go.microsoft.com/fwlink/?LinkID=70396

![image](https://cloud.githubusercontent.com/assets/14539/12872440/aa940654-cda2-11e5-9ac1-b6c20893fb8b.png)

Thanks!

**Comment by IoTGirl** [comment]
Hi Peter,
The link is now fixed. However, if you just click the box and not the text link you do not have to visit the web page.
Sincerely,
IoTGirl
