### ISSUE TITLE
There should be no SPI1 in the RP2_Pinout.png 

### ISSUE THREAD

**Issue by kouji6309** [ms-iot/content#807]
https://github.com/ms-iot/content/blob/develop/images/PinMappings/RP2_Pinout.png

Like the title, there should be no SPI1 in this picture.
如同標題，圖片中應該沒有SPI1。

**Comment by dankuo** [comment]
You are correct. SPI1 is no longer available and the pins have been reallocated as GPIO. We will be updating the diagram shortly.

Thanks!
