### ISSUE TITLE
typo and spacing on main site page

### ISSUE THREAD

**Issue by athousandwords** [ms-iot/content#859]
On the first page, there's a missing space, and possibly a missing article?
now:  "Purchase Raspberry Pi3"
change to:  "Buy a Raspberry Pi 3"
![image](https://cloud.githubusercontent.com/assets/13457780/14336308/4fcbc722-fc17-11e5-910f-42829d7a2aa9.png)

Also, I think the link lists (here and elsewhere on the page) don't have enough vertical space between lines. For example, in the current live site, there's a lot more air between links: 
![image](https://cloud.githubusercontent.com/assets/13457780/14336284/10002142-fc17-11e5-9036-d692e4fb3c8a.png)

**Comment by ivorb** [comment]
Typo fixed, spacing I'll take a look at
