### ISSUE TITLE
Wireless-AC-7260-minnowboard

### ISSUE THREAD

**Issue by ewfian** [ms-iot/content#890]
how to support Intel® Dual Band Wireless-AC 7260 device in windows iot,help me!

**Comment by IoTGirl** [comment]
Hi ewfian,

Intel supports their hardware running IoTCore at https://software.intel.com/en-us/node/622251.   

Microsoft does support some hardware as well and that list is available here: https://developer.microsoft.com/en-us/windows/iot/win10/SupportedInterfaces.htm

Sincerely,
IoTGirl
