### ISSUE TITLE
Support others the raspberry pi

### ISSUE THREAD

**Issue by nmocruz** [ms-iot/content#895]
Raspberry pi is the most popular board, but if window 10 IoT dont not support devices other than this it will be hard to be in the market, or at least get adopted by the community

**Comment by IoTGirl** [comment]
Hi nmocruz,

Microsoft distributes images for Raspberry Pi 2 & 3, DragonBoard 410c & MinnowBoard Max (and Turbot with the same image). You can also build a custom image using the instructions at https://msdn.microsoft.com/en-us/library/windows/hardware/dn916104(v=vs.85).aspx. 

As for other boards and chipsets, third parties can build their own BSPs like Toradex has done for the NVidia T30.  If there is a board that you would like to create an IoT Core image against, Microsoft recommends that you work with the Silicon Vendor to create a custom BSP.

Sincerely,
IoTGirl
