### ISSUE TITLE
Japanese version manual.

### ISSUE THREAD

**Issue by fumiya-kume** [ms-iot/content#910]
Do you plan to create a Japanese version of the manual? If you are not, may I create a Japanese version of the manual?

**Comment by stephenhuang** [comment]
we are currently looking at localization options- with the site always changing it becomes a challenge to keep up.

**Comment by stephenhuang** [comment]
Looks like we are going to be English only for now. Theres a lot of overhead and maintenance with our site (as it is ever changing). We may localize the home pages in the future. 
Thank you for reaching out.
