### ISSUE TITLE
Blue screen of death upon installing Windows IoT Insider Preview

### ISSUE THREAD

**Issue by bosung90** [ms-iot/content#932]
I am getting blue screen of death upon installing and starting up Windows IoT. I tried with Build 14376 and 14366 both blue screen of death, although slightly different (not useful) stop code.

**Comment by IoTGirl** [comment]
Hi Bosung,
Please look at the forums for help on this issue. [https://social.msdn.microsoft.com/Forums/en-US/home?forum=WindowsIoT&sort=relevancedesc&brandIgnore=True&searchTerm=blue+screen](https://social.msdn.microsoft.com/Forums/en-US/home?forum=WindowsIoT&sort=relevancedesc&brandIgnore=True&searchTerm=blue+screen) 
Sincerely,
IoTGirl
