### ISSUE TITLE
Can't access "Wireless 3D Printer Project" page.

### ISSUE THREAD

**Issue by ianlee74** [ms-iot/content#938]
The link from [here](https://github.com/ms-iot/content/blob/develop/en-US/Docs/WhatsNew.md) to [here](https://developer.microsoft-int.com/en-us/windows/iot/docs/3dprintserver) doesn't work. Gives "access denied".

**Comment by adamgoodbar** [comment]
Needs the URL to be updated from microsoft-int.com to microsoft.com

**Comment by IoTGirl** [comment]
Hi Ian,

This has been moved in the new WindowsOnDevices site.  Please refer to https://developer.microsoft.com/en-us/windows/iot/docs/3dprintserver

Sincerely,
IoTGirl

**Comment by IoTGirl** [comment]
NOTE: To find the new location, go to WindowsOnDevices.Com and use the left menu to find the hardware section.  If you click in there it is a sub topic.
