### ISSUE TITLE
Broken Links ?

### ISSUE THREAD

**Issue by obastemur** [ms-iot/content#956]
See original discussion at https://github.com/Microsoft/ChakraCore/issues/1428

**Comment by IoTGirl** [comment]
Please provide the complete set of steps to see the issue.  Note that the same issue was just closed [https://github.com/ms-iot/content/issues/933](https://github.com/ms-iot/content/issues/933)

It is also being tracked at [https://social.msdn.microsoft.com/Forums/en-US/f717b6f0-658e-423c-94f0-ad5d7522e630/microsoft-developer-site-profuse-404-errors?forum=WindowsIoT](https://social.msdn.microsoft.com/Forums/en-US/f717b6f0-658e-423c-94f0-ad5d7522e630/microsoft-developer-site-profuse-404-errors?forum=WindowsIoT)

**Comment by IoTGirl** [comment]
The error on the MSDN issue has been fixed.  Closing.

**Comment by munyirik** [comment]
Links are broken again. Try searching for 'lightning' and clicking on the first link presented. You'll get page not found.
Can we please redirect the old links to the new links?

**Comment by IoTGirl** [comment]
Please provide the failing links so that they can be traced.

**Comment by obastemur** [comment]
>  Try searching for 'lightning' and clicking on the first link presented. You'll get page not found.

## 

> See original discussion at Microsoft/ChakraCore#1428

**Comment by ivorb** [comment]
currently testing redirects in staging - should be fixed within 24 hours

**Comment by ivorb** [comment]
Redirects have been put in place a little while back, if you are still seeing an issue please open a new issue and assign it directly to me.  Thanks!
