### ISSUE TITLE
Remove "cylon wiring" sample

### ISSUE THREAD

**Issue by munyirik** [ms-iot/content#961]
I believe this page was created by mistake - https://developer.microsoft.com/en-us/windows/iot/samples/cylonservowiring

It's just the cylon servo sample duplicated.

**Comment by munyirik** [comment]
cc @msalehmsft

**Comment by stephenhuang** [comment]
Can you clarify add links for the duplicates. This way I can make sure i'm not deleting the wrong file

**Comment by munyirik** [comment]
My title is misleading. Here's the problem.
- https://developer.microsoft.com/en-us/windows/iot/samples/cylonservowiring has nothing to do with wiring. 
- The title says 'servo' but there's no servo in the sample. The instructions are to blink and LED.
- The topic 'Cylon servo controller' in https://developer.microsoft.com/en-us/windows/iot/samples should say something like 'Cylon samples' - the description should say something like 'control a servo and blink and LED with Cylon."
