### ISSUE TITLE
Wrong Node.js hello world link.

### ISSUE THREAD

**Issue by munyirik** [ms-iot/content#963]
Issues
- The hello world link is just the same as the blinky link (there was a hello world page that had a simple server...not sure where it went)
- 'N' in one of the links is capitalized and one is not.

![image](https://cloud.githubusercontent.com/assets/8389594/17779010/000e9652-651b-11e6-8d86-f06699b9db40.png)

**Comment by stephenhuang** [comment]
Fixed
