### ISSUE TITLE
Link to Windows Developer Portal broken

### ISSUE THREAD

**Issue by ChristianBeier** [ms-iot/content#970]
Hi,
on https://developer.microsoft.com/en-us/windows/iot/Docs/GetStarted/noobs/getstartedstep2
the link to Windows Developer Portal is broken.

Same for https://developer.microsoft.com/en-us/windows/iot/docs/setupwifi

**Comment by IoTGirl** [comment]
Windows Device portal should be [https://developer.microsoft.com/windows/iot/docs/deviceportal](https://developer.microsoft.com/windows/iot/docs/deviceportal)

**Comment by ivorb** [comment]
Fixed, will go live shortly
