### ISSUE TITLE
Document the IoTStartupTask

### ISSUE THREAD

**Issue by TylerMSFT** [ms-iot/content#971]
I reference the IoTStartupTask but we don't have it documented.  Here's some info about it:

It is unique to IoT and not supported in store apps as it essentially runs as a headless service with a very large memory cap. It is part of the IoT package. Below is sample code IoT has put out that uses it:

https://github.com/ms-iot/samples/tree/develop/BlinkyHeadless 

Here is the portion of the manifest referencing it, note the IoT-specific namespace.

<Extension Category="windows.backgroundTasks" EntryPoint="BlinkyHeadlessCS.StartupTask">
          <BackgroundTasks>
            <iot:Task Type="startup" />
          </BackgroundTasks>
        </Extension>

**Comment by TylerMSFT** [comment]
Heya,

Not sure what I’m supposed to do with this.

Tyler

**Comment by IoTGirl** [comment]
Hi Tyler,
We are not sure what to do with this either so I will close it assuming there is not issue here at this point.

NOTE: See [https://developer.microsoft.com/en-us/windows/iot/docs/commandlineutils](https://developer.microsoft.com/en-us/windows/iot/docs/commandlineutils) for IoTStartup task usage.

Sincerely,
IoTGirl
