### ISSUE TITLE
I2cDevice.GetDefault() in I2C Overview section

### ISSUE THREAD

**Issue by matsujirushi** [ms-iot/content#980]
Mistake?
https://social.msdn.microsoft.com/Forums/en-us/391866a3-79c6-44c3-95af-d00363459114/i2cdevicegetdefault-method?forum=WindowsIoT

**Comment by ooeygui** [comment]
Can you post a link to where you see the bug?

**Comment by matsujirushi** [comment]
Oh... Already fixed.
https://github.com/ms-iot/content/commit/ddc6f4d7bea13eb2b41d32d1a4a8fc14f18f95d3
