### ISSUE TITLE
PI2: if LAN connects and a MediaElement playing, SpeechRecognizer does not work

### ISSUE THREAD

**Issue by MfCAYO** [ms-iot/content#983]
I still find this pesky bug in the current build 14393.0, I use the USB Audio Card: Sabrent USB External Stereo Sound Adapter, Model AU-EMAC1 according to [Hardware compatibility list](https://developer.microsoft.com/en-us/windows/iot/docs/hardwarecompatlist#Audio).
Any solutions?

**Comment by IoTGirl** [comment]
Hi MfCAYO,
There a quite a few confirmations that the HCL is correct so we are unlikely to be able to explore your issue deeper in the Content Pages of GITHUB.  Rather please take a look at the forums at [https://social.msdn.microsoft.com/Forums/en-US/home?forum=WindowsIoT](https://social.msdn.microsoft.com/Forums/en-US/home?forum=WindowsIoT) for issues on MediaElement, Speech Recognition and Raspberry Pi firmware to gather deeper insight into your issue.

My recommendation would be to try your scenario on other hardware like a Minnow Board or Dragon Board.

Sincerely,
IoTGirl
