### ISSUE TITLE
show only white screen with 410 Dragonboard

### ISSUE THREAD

**Issue by rajeshbarfa** [ms-iot/content#988]
Hello I am using 410 Dragon board with windows 10 iot core

**Comment by IoTGirl** [comment]
Hello Rajesh,
I am closing this issue as you have provided no details as to your error or how and where you get the white screen.  Note that the release notes for each version contain details for such issues. For example [https://social.msdn.microsoft.com/Forums/en-US/163e8227-6e5a-43a5-9f69-499304587a4b/new-flight-14931-released?forum=WindowsIoT](https://social.msdn.microsoft.com/Forums/en-US/163e8227-6e5a-43a5-9f69-499304587a4b/new-flight-14931-released?forum=WindowsIoT) states: 

> Remote Display may fail with the Dragon Board 

Sincerely,
IoTGirl
