### ISSUE TITLE
Seeking VS raspberry pi 3 info

### ISSUE THREAD

**Issue by mattwojo** [ms-iot/content#989]
Some June 2016 feedback from the Dev Center feedback tool that was mis-assigned. Please close if this issue has already been addressed.
"i'm still trying to find information on how to write a program in visual studio to control my raspberry pi 3 using windows iot. i would think this would be one of the first documents i would find looking through all of the pages on this website, but not so."

**Comment by IoTGirl** [comment]
Hi Matt,
All information for putting Windows IoT Core on Raspberry Pi 3 is available on WindowsOnDevices.Com.  Follow the steps at "Getting Started" and choose raspberry Pi as your board.
Sincerely, IoTGirl
